### ISSUE TITLE
future parser error with puppet 3.8.7

### ISSUE THREAD

**Issue by islepnev** [dalenys/puppet-ladvd#1]
Error with future parser enabled on puppet 3.8
Error message:
<pre>
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Evaluation Error: Comparison of: String >= Integer, is not possible. Caused by 'A String is not comparable to a non String'. at /etc/puppet/modules/ladvd/manifests/init.pp:25:28 on node example.com
</pre>

**Comment by rockyluke** [comment]
Fixed in the last commit. Already uploaded on the forge. Thanks ! :)
